services:
  nuvioweb:
    container_name: nuvioweb
    image: ghcr.io/alphasquare404/nuvioweb:stable
    environment:
      NUVIO_SUPABASE_URL: ${NUVIO_SUPABASE_URL:-}
      NUVIO_SUPABASE_ANON_KEY: ${NUVIO_SUPABASE_ANON_KEY:-}
      NUVIO_SUPABASE_FALLBACK_URL: ${NUVIO_SUPABASE_FALLBACK_URL:-}
      YOUTUBE_PROXY_URL: ${YOUTUBE_PROXY_URL:-youtube-proxy.html}
      INTRODB_API_URL: "${INTRODB_API_URL:-https://api.introdb.app/}"
      IMDB_RATINGS_API_BASE_URL: ${IMDB_RATINGS_API_BASE_URL:-}
      IMDB_TAPFRAME_API_BASE_URL: ${IMDB_TAPFRAME_API_BASE_URL:-}
      AVATAR_PUBLIC_BASE_URL: ${AVATAR_PUBLIC_BASE_URL:-}
      UNIQUE_CONTRIBUTIONS_BASE_URL: ${UNIQUE_CONTRIBUTIONS_BASE_URL:-}
      DONATIONS_BASE_URL: ${DONATIONS_BASE_URL:-}
      DONATIONS_DONATE_URL: ${DONATIONS_DONATE_URL:-}
      SPONSOR_NAMES: ${SPONSOR_NAMES:-ragmehos.}
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID:-}
      SIMKL_CLIENT_ID: ${SIMKL_CLIENT_ID:-}
      SIMKL_APP_NAME: ${SIMKL_APP_NAME:-nuvio}
      PREMIUMIZE_CLIENT_ID: ${PREMIUMIZE_CLIENT_ID:-}
    ports:
      - "${NUVIO_PORT:-4173}:80"
    restart: unless-stopped

  trakt-auth-bridge:
    container_name: nuvioweb-trakt-auth-bridge
    image: ghcr.io/alphasquare404/nuvioweb-trakt-auth-bridge:stable
    environment:
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID:-}
      TRAKT_CLIENT_SECRET: ${TRAKT_CLIENT_SECRET:-}
      TRAKT_REDIRECT_URI: ${TRAKT_REDIRECT_URI:-urn:ietf:wg:oauth:2.0:oob}
    restart: unless-stopped

  debrid-api-bridge:
    container_name: nuvioweb-debrid-api-bridge
    image: ghcr.io/alphasquare404/nuvioweb-debrid-api-bridge:stable
    restart: unless-stopped

  external-return-bridge:
    container_name: nuvioweb-external-return-bridge
    image: ghcr.io/alphasquare404/nuvioweb-external-return-bridge:stable
    restart: unless-stopped
    environment:
      NUVIO_WEB_PUSH_PUBLIC_KEY: ${NUVIO_WEB_PUSH_PUBLIC_KEY:-}
      NUVIO_WEB_PUSH_PRIVATE_KEY: ${NUVIO_WEB_PUSH_PRIVATE_KEY:-}
      NUVIO_WEB_PUSH_SUBJECT: ${NUVIO_WEB_PUSH_SUBJECT:-}
